<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Reservation_Control.aspx.cs" Inherits="Restaurant.Reservation_Control" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
        <div>
        </div>
        <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="false" DataKeyNames="ID"
            DataSourceID="SqlDataSource1" EnableModelValidation="True"
            AutoGenerateDeleteButton="True" AutoGenerateEditButton="True">
            <Columns>
                <asp:BoundField DataField="ID" HeaderText="ID" InsertVisible="false" ReadOnly="true" SortExpression="ID"/>
                <asp:BoundField DataField="FirstName" HeaderText ="First Name" SortExpression="FirstName" />
                <asp:BoundField DataField="LastName" HeaderText ="Las Name" SortExpression="LastName" />
                <asp:BoundField DataField="phone_number" HeaderText ="Phone Number" SortExpression="phone_number" />
                <asp:BoundField DataField="email_address" HeaderText ="Email Address" SortExpression="email_address" />
                <asp:BoundField DataField="people_num" HeaderText ="People" SortExpression="people_num" />
                <asp:BoundField DataField="selected_table" HeaderText ="Table" SortExpression="selected_table" />
                <asp:BoundField DataField="reservation_date" HeaderText ="Date" SortExpression="reservation_date" />
                <asp:BoundField DataField="reservation_time" HeaderText ="Time" SortExpression="reservation_time" />
                <asp:BoundField DataField="card_num" HeaderText ="Card" SortExpression="card_num" />
            </Columns>
        </asp:GridView>
        <asp:SqlDataSource ID="SqlDataSource1" runat="server"
           ConnectionString="Data Source=LAPTOP-9K2E0REO;Initial Catalog=Restaurant;Integrated Security=True;Connect Timeout=30;Encrypt=False;TrustServerCertificate=False;ApplicationIntent=ReadWrite;MultiSubnetFailover=False" 
            SelectCommand="SELECT * FROM reservation"
            UpdateCommand="UPDATE reservation Set [FirstName]=@FirstName, [LastName]=@LastName, [phone_number]=@phone_number, [email_address]=@email_address, [people_num]=@people_num, [selected_table]=@selected_table, [reservation_date]=@reservation_date, [reservation_time]=@reservation_time, [card_num]=@card_num Where [ID]=@ID" 
            DeleteCommand="DELETE from reservation Where [ID]=@ID"></asp:SqlDataSource>
    </form>
</body>
</html>
